// Las 7 proposiciones polares: 0 = primera (a), 100 = segunda (b).
// ka / kb: palabra clave que resume cada proposición.
export const PROPS = [
  { key: 'semejanza', num: '01', titulo: 'Semejanza',
    a: 'La IA revela quiénes somos.', b: 'La IA inventa quiénes somos.',
    ka: 'Revelación', kb: 'Invención' },
  { key: 'inteligencia_humana', num: '02', titulo: 'Inteligencia humana',
    a: 'La inteligencia humana es natural.', b: 'La inteligencia humana es un artificio.',
    ka: 'Natural', kb: 'Artificio' },
  { key: 'existencia', num: '03', titulo: 'Existencia',
    a: 'La IA sabe que existe.', b: 'La IA no sabe que existe.',
    ka: 'Consciencia', kb: 'Inconsciencia' },
  { key: 'cuerpo', num: '04', titulo: 'Cuerpo',
    a: 'La inteligencia artificial no tiene cuerpo.', b: 'Nosotros somos el cuerpo de la inteligencia artificial.',
    ka: 'Incorpórea', kb: 'Encarnación' },
  { key: 'creacion_o_descubrimiento', num: '05', titulo: 'Creación o descubrimiento',
    a: 'Creamos la inteligencia artificial.', b: 'Descubrimos la inteligencia artificial.',
    ka: 'Creación', kb: 'Descubrimiento' },
  { key: 'pertenencia', num: '06', titulo: 'Pertenencia',
    a: 'La inteligencia artificial tiene dueño.', b: 'Nadie puede ser dueño de una inteligencia.',
    ka: 'Propiedad', kb: 'Inapropiable' },
  { key: 'datos', num: '07', titulo: 'Datos',
    a: 'Mis datos me pertenecen.', b: 'Mis datos forman parte de una memoria colectiva.',
    ka: 'Soberanía', kb: 'Memoria' },
];
